# Generated by Django 6.0.6 on 2026-07-18 11:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('HEAT_BOOST', 'Heat-Responsive'), ('COLD_BOOST', 'Cold-Responsive'), ('WEATHER_NEUTRAL', 'All-Weather')], max_length=50)),
                ('expire_date', models.DateTimeField(db_index=True)),
                ('shelf_life', models.PositiveIntegerField(editable=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PERISHABLE', 'Perishable Goods'), ('NON_PERISHABLE', 'Non-Perishable Goods'), ('FROZEN', 'Frozen Food'), ('HAZMAT', 'Hazardous Materials')], max_length=50)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('max_shelf_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_prediction', models.PositiveIntegerField()),
                ('order_suggestion', models.PositiveIntegerField()),
                ('target_timing', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shelf'),
        ),
    ]
