# Generated by Django 6.0.6 on 2026-08-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_orderprediction_target_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf_life',
        ),
    ]
