# Generated by Django 6.0.6 on 2026-08-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprediction',
            name='target_timing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='expire_date',
            field=models.DateField(db_index=True),
        ),
    ]
