# Generated by Django 6.0.6 on 2026-08-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_orderprediction_target_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf',
        ),
        migrations.CreateModel(
            name='ProductShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='inventory.product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_allocations', to='inventory.shelf')),
            ],
            options={
                'unique_together': {('product', 'shelf')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shelves',
            field=models.ManyToManyField(through='inventory.ProductShelf', to='inventory.shelf'),
        ),
    ]
