"""
Django settings for core_config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# -------------------- .env setup --------------------
from pathlib import Path
import os
from dotenv import load_dotenv

# Points to project root folder where .env and manage.py live
# call .parent 4 times bcoz .env located at 4rd parent (root folder)
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent

# Load variables from .env into os.environ
load_dotenv(BASE_DIR / ".env")



# -------------------- Security --------------------

# .environ will auto-throw an error if value in .env missing
SECRET_KEY = os.environ['SECRET_KEY'] 

# in .env set to "DEBUG=False" to be Production ; "DEBUG=True" to be Local
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# which URLs are allowed to talk to
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '*').split(',') if host.strip()] # cleans up accidental spaces and trailing commas



# -------------------- Application definition --------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inventory.apps.InventoryConfig',
    'drf_spectacular'
    # celery, httpx, redis, and python-dotenv do not need to be declared inside here (they are Python libraries, not Django app)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_config.wsgi.application'



# -------------------- Database --------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}



# -------------------- Password validation & Internationalization --------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True



# -------------------- Static files (CSS, JavaScript, Images) --------------------

STATIC_URL = 'static/'



# -------------------- Redis & Celery --------------------
# 'celery.py' creates and starts the engine, while 'settings.py' provides the configuration settings for that engine

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # which url to connect (to memurai-redis port)
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json'] # which format to accept
CELERY_TASK_SERIALIZER = 'json'



from celery.schedules import crontab # crontab has options: run at exact times of the day, specific days of the week, or precise calendar dates

# custom hour & minutes, also day gap of running
run_inventory_check_every = int(os.getenv("RUN_INVENTORY_CHECK_EVERY", 1))
run_spoilage_check_every = int(os.getenv("RUN_SPOILAGE_CHECK_EVERY", 1))

h_inv_check = int(os.getenv("H_INV_CHECK", 1))
m_inv_check = int(os.getenv("M_INV_CHECK", 0))

h_spoil_check = int(os.getenv("H_SPOIL_CHECK", 1))
m_spoil_check = int(os.getenv("M_SPOIL_CHECK", 30))

CELERY_BEAT_SCHEDULE = { # when to run task
    'run-predictions-midnight': {
        'task': 'inventory.tasks.run_inventory_check',
        'schedule': crontab(hour=h_inv_check, minute=m_inv_check, day_of_month=f"*/{run_inventory_check_every}"),  # Runs every .. day at 1:00 AM
    },
    'run-spoilage-midnight': {
        'task': 'inventory.tasks.run_spoilage_check',
        'schedule': crontab(hour=h_spoil_check, minute=m_spoil_check, day_of_month=f"*/{run_spoilage_check_every}"), # Runs every .. day at 1:30 AM
    },
}



# -------------------- DRF --------------------
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Tell DRF to use drf-spectacular for generating schemas
}



# -------------------- Swagger & Redoc --------------------
SPECTACULAR_SETTINGS = {
    'TITLE': 'Inventory Management System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
